story6/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

story7/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

story8/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.book_index, name='book_index')
]

story9/urls.py
from django.urls import path, include
from . import views as story9_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/', story9_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(),{'template_name': 'login.html', 'next_page': 'profile'}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(),{'next_page': 'login'} ,name='logout'),
    path('', story9_views.account, name='account')
]

zuh_tdd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('story6.urls','story6'),namespace='story6')),
    path('profile/', include(('story7.urls', 'story7'), namespace='story7')),
    path('books/', include(('story8.urls', 'story8'), namespace='story8')),    
    path('user/',include(('story9.urls', 'story9'), namespace='story9')),
]

story6/models.py
from django.db import models

# Create your models here.

class StatusModel(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django.forms import Form
from django import forms

class StatusForm(Form):
    status = forms.CharField(max_length=300,widget=forms.TextInput(attrs={'class':'validate','id':'Your_Status', 'tag':'Your Status'}))

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'id':'first_name', 'tag':'First Name'}))
    last_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'id':'last_name', 'tag':'Last Name'}))
    email = forms.EmailField(max_length=254, widget=forms.TextInput(attrs={'id':'email', 'tag':'Email','type':'email', 'class':'validate'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)
        widgets = {
            'username': TextInput(attrs={'id':'username', 'tag':'Username'}),
            'password1': TextInput(attrs={'class':'validate','id':'password1', 'tag':'Password', 'type':'password'}),
            'password2': TextInput(attrs={'class':'validate','id':'password2', 'tag':'Password Confirmation', 'type':'password'}),
        }

story6/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .forms import StatusForm
from .models import StatusModel

# Create your views here.

def index(request):
    context = {}
    forms = StatusForm()
    if request.method == 'POST':
        status = request.POST['status']
        new_status  = StatusModel()
        new_status.status = status
        new_status.save()
        return redirect(reverse('story6:index'))
    status_list = StatusModel.objects.all()
    context['forms'] = forms
    context['status_list'] = status_list
    # print(context['status_list'].count())
    return render(request, 'index.html', context)

story7/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

story8/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def book_index(request):
    return render(request, 'book_index.html')

story9/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from story9.forms import SignUpForm

# Create your views here.
def signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('story9:account')
    return render(request, 'signup.html', {'form': form})
    # return HttpResponse('Signup page')

@login_required
def account(request):
    return render(request, 'account.html')
    

story6/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Index
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
<section class="container section center-align">
    {% if user.is_authenticated %}
        <h2 class="center-align">How was your day {{ user.first_name }}?</h2>
    {% else %}
        <h2 class="center-align">How was your day?</h2>
    {% endif %}
    <form action="{% url 'story6:index' %}" method="post">
        {% csrf_token %}
        {% for form in forms %}
            <div class="input-field">
                {{ form }}
                {{ form.label_tag }}
            </div>
        {% endfor %}
        
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>

    {% if status_list.count > 0 %}
        <div class="row">
            <div class="col m4">
                <p>
                    Status
                </p>
            </div>
            <div class="col m4">
                <p>
                    Created Date
                </p>
            </div>
            <div class="col m4">
                <p>
                    Created Time
                </p>
            </div>
        </div>
        {% for status in status_list %}
            <div class="row">
                <div class="col m4">
                    <p class="status_detail">
                        {{ status.status }}
                    </p>
                </div>
                <div class="col m4">
                    <p>
                        {{ status.date }}
                    </p>
                </div>
                <div class="col m4">
                    <p>
                        {{ status.time }}
                    </p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</section>
{% endblock %}

story7/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Profile
{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <div class="col m12 center">
            <div class="switch">
                <label class="lb">
                    Light
                <input type="checkbox" class="cb">
                <span class="lever"></span>
                    Dark
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="fp col m12">
            <img class="" src="{% static './story7/zuh.jpg' %}" alt="zuh">
        </div>
    </div>
    <div class="row">
        <div class="col m12">
            <div id="accordion">
                <h3 class="header">
                    Activities
                </h3>
                <div>
                    <ul>
                        <li>Learning</li>
                        <li>Playing Games</li>
                        <li>Watching Youtube Videos & Films</li>
                    </ul>
                </div>
                <h3>
                    Organizations & Committees
                </h3>
                <div>
                    <ul>
                        <li>Staff of Business and Partnership in BEM Fasilkom UI</li>
                        <li>Staff of Games Division in CGT Batllefield</li>
                        <li>Staff of Mentor in PMB Fasilkom UI</li>
                    </ul>
                </div>
                <h3>
                    Achievements
                </h3>
                <div>
                    <ul>
                        <li>Accepted in Faculty of Computer Science at University of Indonesia</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

story8/templates/book_index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Search Book
{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<section class="container">
    {% if user.is_authenticated %}
      <h2 class="center-align">{{ user.first_name }}, want to find some books?</h2>
    {% else %}
      <h2 class="center-align">Want to find some books?</h2>
    {% endif %}
    <div class="nav-wrapper">
        <form id="searchForm">
          <nav>
              <div class="input-field">
                <input id="search" type="search" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
          </nav>
        </form>
    </div>
    <table class="responsive-table">
        <thead>
          <tr>
              <th><p>Title</p></th>
              <th><p>Author</p></th>
              <th><p>Publisher</p></th>
              <th><p>Image</p></th>
          </tr>
        </thead>

        <tbody class="table-body">
            
        </tbody>
      </table>
</section>
{% endblock %}

story9/templates/account.html
{% extends 'base.html' %}

{% block title %}
Account
{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<section class="container account center">
    <h3>Hello {{ user.first_name }} {{ user.last_name }}</h2>
    <p>It is your username : {{ user.username }}</p>
</section>
{% endblock %}

story9/templates/signup.html
{% extends 'base.html' %}

{% block title %}
Sign Up
{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<section class="container signup">
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        <div>

            {% for field in form %}
                <div class="input-field">
                {{ field }}
                {{ field.label_tag }}
                </div>
                {% if field.help_text %}
                    <small style="color: #10316b">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p class="text-red text-accent-3">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        </div>
        <button class="btn waves-effect waves-light" type="submit" name="action">Sign Up
        <i class="material-icons right">send</i>
        </button>
    </form>
</section>
{% endblock %}

zuh_tdd/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static './css/materialize.css' %}">
    <link rel="stylesheet" href="{% static './css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static './css/jquery-ui.structure.css' %}">
    <link rel="stylesheet" href="{% static './css/jquery-ui.theme.css' %}">
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/jquery-3.4.1.js' %}"></script>
    <script src="{% static './js/jquery-ui.js' %}"></script>
    <script src="{% static './js/materialize.js' %}"></script>
    <script src="{% static './js/script.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="light">
    {% block navbar %}{% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

zuh_tdd/templates/navbar.html
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
        <ul class=" hide-on-small">
            <li><a href="{% url 'story6:index' %}">Status</a></li>
            <li><a href="{% url 'story7:home' %}">Profile</a></li>
            <li><a href="{% url 'story8:book_index' %}">Books</a></li>
            {% if user.is_authenticated %}
            <li class="grey darken-3"><a href="{% url 'story9:logout' %}">Logout</a></li>
            {% else %}
            <li class="grey darken-3"><a href="{% url 'story9:login' %}">Login</a></li>
            <li class="grey darken-3"><a href="{% url 'story9:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
        </div>
    </nav>
</div>